### ISSUE TITLE
Use a git-submodule for lib-armadillo source

### ISSUE THREAD

**Issue by timstaley** [SKA-ScienceDataProcessor/FastImaging#7]
As discussed briefly via Skype, I suggest we use a git submodule to supply the armadillo source. (I've already uploaded a copy of the 7.5 tarball as a [new repository](https://github.com/SKA-ScienceDataProcessor/libarmadillo-mirror)). I have a few reasons for this:
- Reliability and stability: Armadillo is hosted via Sourceforge, which has had [some issues with distributing malware](http://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/) in the past. While I don't think this affects source-tarball downloads, I'm disinclined to rely on sourceforge as our sole point of download.
- Convenience: We're using the latest build of Armadillo (version 7) which is more recent than the system apt-get package on e.g. Ubuntu 16.04. So, we can expect users to need to download and build the code as part of running this library. Might as well provide it as part of the repository.
- Versioning: The Readme currently suggests using Armadillo 7.4, but the Armadillo website states that 7.5 is the latest version. So which should I use? A git submodule with a tested tag removes any ambiguity. 
- Reproducible build options: It seems quite likely that how the armadillo dependency has been built could be important for performance benchmarks - ideally we should integrate the armadillo build into our CMake build scripts, so that the precise build options are documented and can be reliably reproduced.

Purely for convenience, it may be worth pulling in [libgtest](https://github.com/google/googletest) as a submodule, too.

**Comment by cmrlourenco** [comment]
I agree that a fully self-contained build has its advantages, but its not without its drawbacks too:
- **Complex dependency management**: Armadillo depends on other libraries, such as OpenBLAS, LAPACK, BLAS, ARPACK, SuperLU, ATLAS. These, while optional, allow Arma to perform optimally and should always be available if we want to take advantage of modern hardware to its fullest. Also, said libraries probably have dependencies of their own. Where should the line be drawn in terms of OS-provided libs vs. project bundled libs? So far we've been relying on Debian "Stretch" which more or less tracks the latest versions of the packages. Ubuntu is too desktop-centric and was dismissed early on as a possible development environment for us.
- **Unknown build options**: in my opinion, the build options aren't necessarily guaranteed to be reproducible across installations even when the build is self-contained, since every dependency will have its own CMake (or similar) script that will adapt to the host environment. In order to make sure everything is equal regardless of the target, the build must be configured such that all optionals are explicitly specified.
- **Maintenance**: having sub-projects means we'll always be responsible for their successful build across all platforms our project will be built on. Someone might be using an exotic flavour of Linux which, for some obscure reason, will cause the build to fail. Letting distro maintainers worry about external packages sounds a lot better. Also, we're never going to download sources from dodgy services such as Sourceforge; the point is to rely solely on the distro's repositories which tend to be trustworthy.

All this doesn't mean that I'm against the general idea of self containing the build - I just want to ponder on the pros and cons of both approaches. Would you consider standardising on a specific distro for this project?

_Final note_: Google Test [must](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal) be made into a sub-project, but it's easily manageable.

**Comment by timstaley** [comment]
Hi Cesar - good points, and you're right about choosing the line / making sure the whole environment is reproducible. Perhaps we need a different approach - something I've employed elsewhere is to put together a Vagrantfile and deployment scripts so you can test your chosen distro+libs+code on any machine. My only question would then be whether we bundle the deploy scripts here or keep them in a seperate repository - I think marginally I'd go for bundling it here, any thoughts on that? (Obviously all low priority for now, but something to consider. I'd be happy to put deploy/VM scripts together myself since the tools are still all fresh in memory.)

**Comment by timstaley** [comment]
We agreed that for installation, Cesar will work on implementing a statically compiled version of the library and binaries, likely bundled as a .deb package.
